/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import jxl.Sheet;
import jxl.Workbook;
import jxl.read.biff.BiffException;

/**
 *
 * @author fedem
 */
public class Principal extends javax.swing.JFrame {
    
    private FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivo Excel (.xls)", "xls");
    String filePath;
    String dstPath;

    public String getDstPath() {
        return dstPath;
    }

    public void setDstPath(String dstPath) {
        this.dstPath = dstPath;
    }
    int[] longitudCab = {4,5,8,8,4,4,2,10,10,3,1,12,36,2,141};
    int[] longitudR1 =  {4,5,2,22,1,22,10,13,2,6,8,15,23,1,40,76};
    int[] longitudR2 =  {4,5,2,22,36,36,36,109};
    int[] longitudR3 =  {4,5,2,22,36,36,36,109};
    int[] longitudR4 =  {4,5,2,22,40,177};
    int[] longitudPie = {4,5,13,2,8,10,208};
    boolean cab = false;
    boolean pie = false;
    
    public Principal() {
        initComponents();
        filePath="";
        dstPath="";
        jButtonConverter.setEnabled(false);
        jButtonSelectDst.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonExit = new javax.swing.JButton();
        jButtonSearch = new javax.swing.JButton();
        txtFileSource = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButtonConverter = new javax.swing.JButton();
        txtFileDest = new javax.swing.JTextField();
        jButtonSelectDst = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonExit.setText("SALIR");
        jButtonExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonExitMouseClicked(evt);
            }
        });
        getContentPane().add(jButtonExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, 80, 30));

        jButtonSearch.setText("Buscar Archivo");
        jButtonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        txtFileSource.setEnabled(false);
        getContentPane().add(txtFileSource, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 400, -1));

        jLabel1.setText("Ruta del Archivo Excel");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 120, 20));

        jButtonConverter.setText("Convertir a TXT");
        jButtonConverter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConverterActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonConverter, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, -1, -1));

        txtFileDest.setEnabled(false);
        getContentPane().add(txtFileDest, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 400, -1));

        jButtonSelectDst.setText("Guardar en...");
        jButtonSelectDst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSelectDstActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSelectDst, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        jLabel2.setText("Directorio donde se guardara el archivo");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchActionPerformed
        // TODO add your handling code here:
        JFileChooser dlg = new JFileChooser();
        dlg.setFileFilter(filter);
        dlg.setAcceptAllFileFilterUsed(false);
        int option = dlg.showOpenDialog(this);
        if(option == JFileChooser.APPROVE_OPTION){
            String fil = dlg.getSelectedFile().getPath();
            String file = dlg.getSelectedFile().toString();
            //File fichero =dlg.getSelectedFile();
            String ext = getExtension(file);
            System.out.println(ext);
            if(ext.equals("") || !ext.equals("xls")){
                lanzarAlerta("el archivo no tiene una extension valida");
            }else{
                txtFileSource.setText(file);
                filePath = file;
                jButtonSelectDst.setEnabled(true);
            }
            
            
        }
    }//GEN-LAST:event_jButtonSearchActionPerformed

    private void jButtonConverterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConverterActionPerformed
        
        try {
            // TODO add your handling code here:
            Workbook workbook = Workbook.getWorkbook(new File(filePath));
            Sheet sheet = workbook.getSheet(0);
            String nombre ;
            String ruta;
            String formato ="";
            String codigo = "";
            ruta = getDstPath();
            File archivo = new File(ruta);
            lanzarAlerta(ruta);
            BufferedWriter bw;
            bw = new BufferedWriter(new FileWriter(archivo));
            for (int fila = 0; fila < sheet.getRows(); fila++){
                  for (int columna = 0; columna < sheet.getColumns(); columna++){
                      if(columna == 0){
                          codigo = sheet.getCell(columna, fila).getContents();
                          System.out.println("NUEVO CODIGO" + codigo);
                      }
                      nombre = sheet.getCell(columna, fila).getContents();
                      
                      if(codigo.equals("2110") && columna <= 14){
                          formato = "%-"+longitudCab[columna]+"s";
                          bw.write(String.format(formato, nombre));
                      }else if(codigo.equals("2210") && columna <= 15){
                          formato = "%-"+longitudR1[columna]+"s";
                          bw.write(String.format(formato, nombre));
                      }else if(codigo.equals("2220") && columna <= 7){
                          formato = "%-"+longitudR2[columna]+"s";
                          bw.write(String.format(formato, nombre));
                      }else if(codigo.equals("2230") && columna <= 7){
                          formato = "%-"+longitudR3[columna]+"s";
                          bw.write(String.format(formato, nombre));
                      }else if(codigo.equals("2240") && columna <= 5){
                          formato = "%-"+longitudR4[columna]+"s";
                          bw.write(String.format(formato, nombre));
                      }else if(codigo.equals("2910") && columna <= 6){
                          formato = "%-"+longitudPie[columna]+"s";
                          bw.write(String.format(formato, nombre));
                      }
                      System.out.println(formato);
                  }
                  bw.newLine();
                  codigo = "";
             }
             bw.close();
        } catch (IOException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            lanzarAlerta("ERROR?");
        } catch (BiffException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex); 
            lanzarAlerta("Error de formato");
        }
    }//GEN-LAST:event_jButtonConverterActionPerformed

    private void jButtonExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonExitMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButtonExitMouseClicked

    private void jButtonSelectDstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSelectDstActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.setCurrentDirectory(new java.io.File("."));
        chooser.setDialogTitle("Guardar en...");
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        chooser.setAcceptAllFileFilterUsed(false);
        if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) { 
            String file = chooser.getSelectedFile().toString();
            txtFileDest.setText(file);
            setDstPath(chooser.getSelectedFile()+"\\ARCHIVORESULTANTE.TXT");
            jButtonConverter.setEnabled(true);
            /*System.out.println("getCurrentDirectory(): " 
               +  chooser.getCurrentDirectory());
            System.out.println("getSelectedFile() : " 
               +  chooser.getSelectedFile());
            */
        } else {
            lanzarAlerta("Debe seleccionar destino");
        }

    }//GEN-LAST:event_jButtonSelectDstActionPerformed

    private void lanzarAlerta(String msj){
        JOptionPane.showMessageDialog(null, msj);
    }
    
    public static String getExtension(String filename) {
            int index = filename.lastIndexOf('.');
            if (index == -1) {
                  return "";
            } else {
                  return filename.substring(index + 1);
            }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonConverter;
    private javax.swing.JButton jButtonExit;
    private javax.swing.JButton jButtonSearch;
    private javax.swing.JButton jButtonSelectDst;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtFileDest;
    private javax.swing.JTextField txtFileSource;
    // End of variables declaration//GEN-END:variables
}
